{
 "title": "Celestia light node dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "nodeid", "query": "${VAR_NODEID}" },
   { "name": "job_version", "query": { "query": "label_values(exported_job)" } }
  ]
 },
 "panels": [
  {
   "title": "Node id",
   "type": "text",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"height:100%; display:flex; justify-content:center; align-items:center;\">\n    <div style=\"text-align:center;\">\n        <h4>${nodeid}</h4>\n    </div>\n</div>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - ((node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) / node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Free Disk",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype=\"ext4\"}"
    }
   ]
  },
  {
   "title": "Run time",
   "type": "stat",
   "description": "Run time since last restart",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_runtime_counter_in_seconds{exported_instance=\"$nodeid\",exported_job=\"$job_version\"}"
    }
   ]
  },
  {
   "title": "Network head",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "das_network_head{exported_instance=\"$nodeid\",exported_job=\"$job_version\"}"
    }
   ]
  },
  {
   "title": "das sampled chain head head",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "das_sampled_chain_head{exported_instance=\"$nodeid\"}"
    }
   ]
  },
  {
   "title": "Total synced headers",
   "type": "stat",
   "description": "Celestia total synced headers since last restart",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_synced_headers{exported_instance=\"$nodeid\",exported_job=\"$job_version\"}"
    }
   ]
  },
  {
   "title": "Das sampled headers count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "sum(das_sampled_headers_counter{exported_job=\"$job_version\",exported_instance=\"$nodeid\"})",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Last pfb time",
   "type": "stat",
   "description": "Last  pfb time, if 1970-01-01 08:00:00 that means no pfb transactions yet.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_pfb_timestamp{exported_instance=\"$nodeid\",exported_job=\"$job_version\"}"
    }
   ]
  },
  {
   "title": "PFB count",
   "type": "stat",
   "description": "Total count of submitted PayForBlob transactions",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pfb_count{exported_instance=\"$nodeid\",exported_job=\"$job_version\"}"
    }
   ]
  }
 ]
}